### ISSUE TITLE
Polymorphism Support

### ISSUE THREAD

**Issue by urgent** [kappa-db/kappa-core#12]
Is polymoprhism supported for kappa-core, for instance if I want to run it in the browser?

I tried with browserify, and received:

> Error: Cannot find module '/node_modules/multifeed/package.json'

**Comment by hackergrrl** [comment]
You can. For hypercore storage you'd use something like https://github.com/random-access-storage/random-access-web and for leveldb (for kappa views) you could use perhaps
https://github.com/Level/level-js

I kinda think the performance of level-js in particular will end up being prohibitively slow, but it ought to work fine.

**Comment by urgent** [comment]
Thank you!

**Comment by DougAnderson444** [comment]
`memdb` [looks like it works in the browser](https://www.npmjs.com/package/memdb) via `Browerify` so is changing it for kappa views really needed?

@urgent did you get it to work in the browser?
