### ISSUE TITLE
README incorrect for storage parameter

### ISSUE THREAD

**Issue by gmaclennan** [kappa-db/kappa-core#17]
The README says:

> Create a new kappa-core database.
>
> - `storage` is an instance of [random-access-storage](https://github.com/random-access-storage). If a string is given, [random-access-file](https://github.com/random-access-storage/random-access-storage) is used with the string as the filename.

I _think_ `storage` should be a function that returns an instance of random access storage?

**Comment by hackergrrl** [comment]
Correct! I thought it would be less confusing to write it this way, but
I'd merge a PR that changed it to what you're proposing.

**Comment by hackergrrl** [comment]
fixed (also in multifeed's readme)
